USE atv_procedure
CREATE PROCEDURE P_ATV_PROCEDURES_EMPRESTIMOS
(
	@Id_livro_fk INT,
	@Id_cliente_fk INT
)
AS
	BEGIN
	SET NOCOUNT ON
		INSERT INTO tbl_emprestimos (id_livro_fk, id_cliente_fk)
		VALUES (@Id_livro_fk, @Id_cliente_fk)
	END
GO
 
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 1, 1;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 2, 2;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 3, 3;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 4, 4;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 5, 5;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 6, 6;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 7, 7;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 8, 8;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 9, 9;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 10, 10;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 11, 11;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 12, 12;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 13, 13;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 14, 14;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 15, 15;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 16, 16;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 17, 17;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 18, 18;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 19, 19;
EXEC P_ATV_PROCEDURES_EMPRESTIMOS 20, 20;
 

CREATE PROCEDURE P_REGISTRAR_EMPRESTIMO
(
	@Id_emprestimo INT,
	@Id_livro INT
)
AS
	BEGIN
		SET NOCOUNT ON
		BEGIN TRANSACTION
			IF EXISTS (
				SELECT 1
				FROM tbl_livros
				WHERE qtd_livro = 0 AND id_livro = @Id_livro
			)
			BEGIN
				PRINT 'Livro indisponível ou sem estoque.'
				ROLLBACK;
			END
			ELSE
				BEGIN
					UPDATE tbl_emprestimos
					SET data_emprestimo = GETDATE(),
					data_previsao_devolucao = DATEADD(DAY, 7, GETDATE()) -- Adiciona 7 dias
					WHERE id_emprestimo = @Id_emprestimo;
 
					UPDATE tbl_emprestimos
					SET qtd_livros_alugados = qtd_livros_alugados + 1
					WHERE id_emprestimo = @Id_emprestimo;
 
					UPDATE tbl_emprestimos
					SET possui_livro_alugado = 1
					WHERE id_emprestimo = @Id_emprestimo

					UPDATE tbl_livros
					SET qtd_livro = qtd_livro - 1
					WHERE id_livro = @Id_livro;

					UPDATE tbl_livros
					SET disponivel = 0
					WHERE id_livro = @Id_livro AND qtd_livro = 0;
					COMMIT;
			END
	END

UPDATE tbl_emprestimos
SET qtd_livros_alugados = 0

GO
EXEC P_REGISTRAR_EMPRESTIMO 1, 1
EXEC P_REGISTRAR_EMPRESTIMO 2, 2
EXEC P_REGISTRAR_EMPRESTIMO 3, 3
EXEC P_REGISTRAR_EMPRESTIMO 4, 4
EXEC P_REGISTRAR_EMPRESTIMO 5, 5
EXEC P_REGISTRAR_EMPRESTIMO 6, 6
EXEC P_REGISTRAR_EMPRESTIMO 7, 7
EXEC P_REGISTRAR_EMPRESTIMO 8, 8
EXEC P_REGISTRAR_EMPRESTIMO 9, 9
EXEC P_REGISTRAR_EMPRESTIMO 10, 10
EXEC P_REGISTRAR_EMPRESTIMO 11, 11
EXEC P_REGISTRAR_EMPRESTIMO 12, 12
EXEC P_REGISTRAR_EMPRESTIMO 13, 13
EXEC P_REGISTRAR_EMPRESTIMO 14, 14
EXEC P_REGISTRAR_EMPRESTIMO 15, 15
EXEC P_REGISTRAR_EMPRESTIMO 16, 16
EXEC P_REGISTRAR_EMPRESTIMO 17, 17
EXEC P_REGISTRAR_EMPRESTIMO 18, 18
EXEC P_REGISTRAR_EMPRESTIMO 19, 19
EXEC P_REGISTRAR_EMPRESTIMO 20, 20
GO

SELECT * FROM tbl_emprestimos;
SELECT * FROM tbl_livros;
SELECT * FROM tbl_clientes;

TRUNCATE TABLE TBL_EMPRESTIMOS;

DROP PROCEDURE P_ATV_PROCEDURES_EMPRESTIMOS;
GO
DROP PROCEDURE P_REGISTRAR_EMPRESTIMO;
GO
 
UPDATE tbl_livros
SET qtd_livro = 0, disponivel = 0
WHERE id_livro = 14

UPDATE tbl_livros
SET qtd_livro = 5

